export const filederPartsActiveInactive = {
    'base': true,
    'wrist': true,
    'logo': true,
    'f1': true,
    'f2': true,
    'f3': true,
    'f4': true,
    'f5': true,
    'f6': true,
    'f7': true,
    'f8': true,
    't1': true,
    't2': true,
    'piping': true,
    'welting': true,
    'palm': true,
    'web': true,
    'lace': true,
    'hood': false,
    'hoodstitch': false,
    'stitch': true,
    'e': false,
}