export const tabConstants = {
    GLOVE_FOUNDATION: 'Glove Foundation',
    LEATHER_DESIGN: 'Leather & Design',
    PERSONAL_EMBROIDERY: 'Embroidery & Personalization',
    COMMON_COLORS: [
        {name: "Dark Camel", code: "darkcamel", rgb: "center center rgb(114, 70, 37)"},
        {name: "Camel", code: "camel", rgb: "center center rgb(193, 154, 107)"},
        {name: "Light Blue", code: "lightblue", rgb: "center center rgb(191, 239, 255)"},
        {name: "Pink", code: "pink", rgb: "center center rgb(255,192,203)"},
        {name: "Lemon Yellow", code: "lemonyellow", rgb: "center center rgb(255, 244, 79)"},
        {name: "Orange", code: "orange", rgb: "center center rgb(255, 165, 0)"},
        {name: "Natural", code: "natural", rgb: "center center rgb(255, 255, 0)"},
        {name: "Toffee", code: "toffee", rgb: "center center rgb(117, 81, 57)"},
        {name: "Dark Purple", code: "dark purple", rgb: "center center rgb(48, 25, 52)"},
        {name: "Royal Blue", code: "royal blue", rgb: "#4169e1"},
        {name: "Red", code: "red", rgb: "center center rgb(255, 0, 0)"},
        {name: "Dark Green", code: "darkgreen", rgb: "center center rgb(0,100,0)"},
        {name: "Navy", code: "navy", rgb: "center center rgb(0, 0, 128)"},
        {name: "Black", code: "black", rgb: "center center rgb(0, 0, 0)"},
        {name: "Brown", code: "brown", rgb: "center center rgb(150, 75, 0)"},
        {name: "Wine", code: "wine", rgb: "center center rgb(177, 18, 38)"},
        {name: "White", code: "white", rgb: "center center rgb(255, 255, 255)"},
        {name: "Gray", code: "gray", rgb: "center center rgb(220, 220, 220)"},
        {name: "Dark Gray", code: "darkgray", rgb: "center center rgb(169, 169, 169)"},
    ],
    PART_NAMES: [
        {name: 'wrist'},
        {name: 'logo'},
        {name: 'f1'},
        {name: 'f2'},
        {name: 'f3'},
        {name: 'f4'},
        {name: 'f5'},
        {name: 'f6'},
        {name: 'f7'},
        {name: 'f8'},
        {name: 't1'},
        {name: 't2'},
        {name: 'piping'},
        {name: 'welting'},
        {name: 'palm'},
        {name: 'web'},
        {name: 'lace'},
        {name: 'hood'},
        {name: 'stitch'},
    ]
    // GLOVE_FOUNDATION: 'Base',
    // LEATHER_DESIGN: 'Colors',
    // PERSONAL_EMBROIDERY: 'Personalize'
}